language: ruby
sudo: false
cache: bundler
rvm:
- 2.0.0
- 2.1.10
- 2.2.7
- 2.3.4
- 2.4.1
before_install:
- travis_retry gem update --system
deploy:
  provider: rubygems
  api_key:
    secure: AkaGJCc8pCkVY5IPVa3dwvS4wvPlMHHkyqrIpi8G5nFiDFjtHjWY7tDUfFCxMrF7WNXWVNg/bgkzwfvoAZcvGVU9grzCDqTC9uvsF5V3hB5FikyQ6h++mJRCiYzfLbjzyAT3FAuB49dXYeZR/eOKPPqn9jMAQPyHd6+PAGE3BeI=
  gem: tracking_number
  on:
    tags: true
    repo: jkeen/tracking_number

